#!/usr/bin/env python3
# Embeds a .namb model file into a C header as a 4-byte-aligned const array.
# The Terrarium has no SD card, so the model is compiled into QSPI flash.
#
# Usage: gen_model_data.py <model.namb> <model_data.h>

import sys


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_model_data.py <input.namb> <output.h>")
    src, dst = sys.argv[1], sys.argv[2]
    data = open(src, "rb").read()

    lines = [
        "#pragma once",
        "// Auto-generated by gen_model_data.py — do not edit by hand.",
        f"// Source: {src} ({len(data)} bytes)",
        "#include <cstdint>",
        "",
        f"alignas(4) static const uint8_t kModelData[] = {{",
    ]
    for i in range(0, len(data), 12):
        chunk = data[i : i + 12]
        lines.append("    " + "".join(f"0x{b:02x}, " for b in chunk).rstrip())
    lines.append("};")
    lines.append(f"static const uint32_t kModelDataLen = {len(data)};")
    lines.append("")

    open(dst, "w").write("\n".join(lines))


if __name__ == "__main__":
    main()
