#ifndef NAM_MODEL_H
#define NAM_MODEL_H

#include <stdint.h>

/* Generated by nam2c.py - do not edit */

#ifndef NAM_MAX_BUFFER_SIZE
#define NAM_MAX_BUFFER_SIZE 64
#endif

/* Define NAM_DTCM to place weights in fast memory (e.g. DTCM on Cortex-M7) */
#ifndef NAM_DTCM
#define NAM_DTCM
#endif

#define NAM_IN_CHANNELS 1
#define NAM_OUT_CHANNELS 1
#define NAM_SAMPLE_RATE 48000.0f

/*
 * Power-of-2 circular ring buffers — no memmove rewinds.
 * Reads/writes use (index & mask) for zero-cost wrapping.
 */
#define NAM_RB_FRAMES_128  128
#define NAM_RB_FRAMES_256  256
#define NAM_RB_FRAMES_512  512
#define NAM_RB_FRAMES_1024  1024
#define NAM_RB_FRAMES_2048  2048
#define NAM_RB_MASK_128  (NAM_RB_FRAMES_128 - 1)
#define NAM_RB_MASK_256  (NAM_RB_FRAMES_256 - 1)
#define NAM_RB_MASK_512  (NAM_RB_FRAMES_512 - 1)
#define NAM_RB_MASK_1024  (NAM_RB_FRAMES_1024 - 1)
#define NAM_RB_MASK_2048  (NAM_RB_FRAMES_2048 - 1)

typedef struct nam_state_t nam_state_t;

/* Initialize model state (call once) */
void nam_init(nam_state_t* state);

/* Reset model state (clears ring buffers) */
void nam_reset(nam_state_t* state);

/* Process num_frames of audio */
/* input: float[NAM_IN_CHANNELS][num_frames] */
/* output: float[NAM_OUT_CHANNELS][num_frames] */
void nam_process(nam_state_t* state, const float* const* input, float* const* output, int num_frames);

/* Compile with -DNAM_PROFILE_ACTIVATIONS to track peak activation values. */
/* After processing, call nam_get_act_peak() for the recommended act_scale. */
#ifdef NAM_PROFILE_ACTIVATIONS
float nam_get_act_peak(void);
int nam_get_num_layers(void);
float nam_get_layer_peak(int layer);
#endif

/* State struct - sizes depend on model architecture */
struct nam_state_t {
    /* Layer array 0, layer 0: dil=1 rf=5 pow2=128 — ring buf in DTCM (file-scope) */
    int la0_l0_conv_rb_wpos;

    /* Layer array 0, layer 1: dil=3 rf=15 pow2=128 — ring buf in DTCM (file-scope) */
    int la0_l1_conv_rb_wpos;

    /* Layer array 0, layer 2: dil=7 rf=35 pow2=128 — ring buf in DTCM (file-scope) */
    int la0_l2_conv_rb_wpos;

    /* Layer array 0, layer 3: dil=17 rf=85 pow2=256 — ring buf in DTCM (file-scope) */
    int la0_l3_conv_rb_wpos;

    /* Layer array 0, layer 4: dil=41 rf=205 pow2=512 — ring buf in DTCM (file-scope) */
    int la0_l4_conv_rb_wpos;

    /* Layer array 0, layer 5: dil=101 rf=505 pow2=1024 — ring buf in DTCM (file-scope) */
    int la0_l5_conv_rb_wpos;

    /* Layer array 0, layer 6: dil=239 rf=1195 pow2=2048 */
    float la0_l6_conv_rb[3 * NAM_RB_FRAMES_2048];
    int la0_l6_conv_rb_wpos;
    /* Cache anti-alias padding: keeps p2=2048 SRAM ring buffers in distinct D-cache sets */
    char _rb_pad_la0_l6[1340];

    /* Layer array 0, layer 7: dil=1 rf=5 pow2=128 — ring buf in DTCM (file-scope) */
    int la0_l7_conv_rb_wpos;

    /* Layer array 0, layer 8: dil=3 rf=15 pow2=128 — ring buf in DTCM (file-scope) */
    int la0_l8_conv_rb_wpos;

    /* Layer array 0, layer 9: dil=7 rf=35 pow2=128 — ring buf in DTCM (file-scope) */
    int la0_l9_conv_rb_wpos;

    /* Layer array 0, layer 10: dil=17 rf=85 pow2=256 — ring buf in DTCM (file-scope) */
    int la0_l10_conv_rb_wpos;

    /* Layer array 0, layer 11: dil=41 rf=205 pow2=512 — ring buf in DTCM (file-scope) */
    int la0_l11_conv_rb_wpos;

    /* Layer array 0, layer 12: dil=101 rf=505 pow2=1024 — ring buf in DTCM (file-scope) */
    int la0_l12_conv_rb_wpos;

    /* Layer array 0, layer 13: dil=239 rf=1195 pow2=2048 */
    float la0_l13_conv_rb[3 * NAM_RB_FRAMES_2048];
    int la0_l13_conv_rb_wpos;
    /* Cache anti-alias padding: keeps p2=2048 SRAM ring buffers in distinct D-cache sets */
    char _rb_pad_la0_l13[1328];

    /* Layer array 0, layer 14: dil=1 rf=14 pow2=128 — ring buf in DTCM (file-scope) */
    int la0_l14_conv_rb_wpos;

    /* Layer array 0, layer 15: dil=13 rf=182 pow2=256 — ring buf in DTCM (file-scope) */
    int la0_l15_conv_rb_wpos;

    /* Layer array 0, layer 16: dil=1 rf=5 pow2=128 — ring buf in DTCM (file-scope) */
    int la0_l16_conv_rb_wpos;

    /* Layer array 0, layer 17: dil=3 rf=15 pow2=128 — ring buf in DTCM (file-scope) */
    int la0_l17_conv_rb_wpos;

    /* Layer array 0, layer 18: dil=7 rf=35 pow2=128 — ring buf in DTCM (file-scope) */
    int la0_l18_conv_rb_wpos;

    /* Layer array 0, layer 19: dil=17 rf=85 pow2=256 — ring buf in DTCM (file-scope) */
    int la0_l19_conv_rb_wpos;

    /* Layer array 0, layer 20: dil=41 rf=205 pow2=512 — ring buf in DTCM (file-scope) */
    int la0_l20_conv_rb_wpos;

    /* Layer array 0, layer 21: dil=101 rf=505 pow2=1024 — ring buf in DTCM (file-scope) */
    int la0_l21_conv_rb_wpos;

    /* Layer array 0, layer 22: dil=239 rf=1195 pow2=2048 */
    float la0_l22_conv_rb[3 * NAM_RB_FRAMES_2048];
    int la0_l22_conv_rb_wpos;

    /* Layer array 0: fused mode (working buffers on stack) */
    int la0_head_rechannel_rb_wpos;

};

/* Load weights from a flat array (C++ set_weights_ order) */
/* Returns 0 on success, -1 on weight count mismatch */
int nam_load_weights(const float* weights, int num_weights);

#endif /* NAM_MODEL_H */