// NAMPedal — Neural Amp Modeler running on a Daisy Pod (pure C inference)
//
// Loads an A2-nano NAM model in .namb (binary) format from the SD card and
// applies it to incoming audio in real time. Model inference uses the C code
// generated by nam2c.py with --dynamic-weights, so a single firmware image
// can run any A2-nano model by swapping the .namb on the SD card.
//
// Controls: Knob 1 = input gain, Knob 2 = output volume, SW1 = bypass toggle.

#include "daisy_pod.h"
#include <cstring>

extern "C" {
#include "nam_model.h"
}

using namespace daisy;

static DaisyPod hw;

static float gain   = 1.0f;
static float volume = 1.0f;
static volatile bool effect_active = false;

// Model state lives in .bss (AXI SRAM). DTCM-resident ring buffers and
// weights are placed there by nam_model.c via NAM_DTCM.
static nam_state_t nam_state;
static bool        model_loaded = false;

static constexpr size_t kMaxBlockSize = NAM_MAX_BUFFER_SIZE;
static float            mono_in[kMaxBlockSize];
static float            mono_out[kMaxBlockSize];

// A2-nano receptive field. Dilations × (kernel_size − 1) summed across layers:
//   layers  0–13: kernel=6,  dilations [1,3,7,17,41,101,239, 1,3,7,17,41,101,239] → 4090
//   layers 14–15: kernel=15, dilations [1,13]                                     →  196
//   layers 16–22: kernel=6,  dilations [1,3,7,17,41,101,239]                      → 2045
static constexpr int kPrewarmSamples = 1 + 4090 + 196 + 2045;

static SdmmcHandler   sdcard;
static FatFSInterface fsi;
static FIL            sd_file;

// File read buffer in .bss (DMA-accessible AXI SRAM).
// A2-nano has 1871 float weights → 7484 bytes payload + 32-byte .namb header.
static constexpr size_t kMaxFileSize = 8 * 1024;
static uint8_t          file_read_buf[kMaxFileSize];

static constexpr uint32_t NAMB_MAGIC = 0x4E414D42; // "NAMB"

// Feed silence through the model until the receptive field is full.
static void Prewarm(int prewarm_samples)
{
    float zero_buf[NAM_MAX_BUFFER_SIZE];
    float out_buf[NAM_MAX_BUFFER_SIZE];
    memset(zero_buf, 0, sizeof(zero_buf));

    float* in_ptrs[NAM_IN_CHANNELS];
    float* out_ptrs[NAM_OUT_CHANNELS];
    for(int i = 0; i < NAM_IN_CHANNELS; i++)
        in_ptrs[i] = zero_buf;
    for(int i = 0; i < NAM_OUT_CHANNELS; i++)
        out_ptrs[i] = out_buf;

    int processed = 0;
    while(processed < prewarm_samples)
    {
        int n = NAM_MAX_BUFFER_SIZE;
        if(n > prewarm_samples - processed)
            n = prewarm_samples - processed;
        nam_process(&nam_state, (const float* const*)in_ptrs, out_ptrs, n);
        processed += n;
    }
}

static bool LoadModel(const char* path)
{
    FRESULT fr = f_open(&sd_file, path, FA_READ);
    if(fr != FR_OK)
    {
        hw.seed.PrintLine("  f_open failed: %d", (int)fr);
        return false;
    }

    UINT file_size = f_size(&sd_file);
    hw.seed.PrintLine("  file size: %u bytes", (unsigned)file_size);
    if(file_size > kMaxFileSize)
    {
        hw.seed.PrintLine("  file too large (max %u)", (unsigned)kMaxFileSize);
        f_close(&sd_file);
        return false;
    }

    // Read in 512-byte chunks (SDMMC DMA transfer-size constraint).
    UINT total_read = 0;
    while(total_read < file_size)
    {
        UINT chunk = file_size - total_read;
        if(chunk > 512)
            chunk = 512;
        UINT bytes_read;
        fr = f_read(&sd_file, file_read_buf + total_read, chunk, &bytes_read);
        if(fr != FR_OK)
        {
            hw.seed.PrintLine(
                "  f_read failed at %u: fr=%d", (unsigned)total_read, (int)fr);
            f_close(&sd_file);
            return false;
        }
        total_read += bytes_read;
    }
    f_close(&sd_file);
    hw.seed.PrintLine("  read OK (%u bytes)", (unsigned)total_read);

    // .namb header (32 bytes):
    //   u32 magic, u16 version, u16 flags, u32 total_size,
    //   u32 weights_offset, u32 num_weights, u32 model_block_size, u32 checksum
    if(total_read < 32)
    {
        hw.seed.PrintLine("  file too small for header");
        return false;
    }

    uint32_t magic;
    memcpy(&magic, file_read_buf, 4);
    if(magic != NAMB_MAGIC)
    {
        hw.seed.PrintLine("  bad magic: 0x%08lX", (unsigned long)magic);
        return false;
    }

    uint32_t weights_offset, num_weights;
    memcpy(&weights_offset, file_read_buf + 12, 4);
    memcpy(&num_weights, file_read_buf + 16, 4);

    hw.seed.PrintLine("  weights: offset=%lu count=%lu",
                      (unsigned long)weights_offset,
                      (unsigned long)num_weights);

    if(weights_offset + num_weights * 4 > total_read)
    {
        hw.seed.PrintLine("  weights extend beyond file");
        return false;
    }

    nam_init(&nam_state);

    const float* weights
        = reinterpret_cast<const float*>(file_read_buf + weights_offset);
    int rc = nam_load_weights(weights, (int)num_weights);
    if(rc != 0)
    {
        hw.seed.PrintLine("  nam_load_weights failed (not an A2-nano model?)");
        return false;
    }

    hw.seed.PrintLine("  prewarming (%d samples)...", kPrewarmSamples);
    uint32_t t0 = System::GetNow();
    Prewarm(kPrewarmSamples);
    hw.seed.PrintLine("  model ready (%lu ms)",
                      (unsigned long)(System::GetNow() - t0));
    return true;
}

static volatile uint32_t cb_count          = 0;
static volatile uint32_t cb_process_cycles = 0;
static volatile uint32_t cb_max_cycles     = 0;

static void AudioCallback(AudioHandle::InterleavingInputBuffer  in,
                          AudioHandle::InterleavingOutputBuffer out,
                          size_t                                size)
{
    // Force FZ/DN in this ISR context.
    __set_FPSCR(__get_FPSCR() | (1U << 24) | (1U << 25));

    cb_count++;
    size_t num_frames = size / 2;

    if(model_loaded && effect_active)
    {
        for(size_t i = 0; i < num_frames; i++)
            mono_in[i] = in[i * 2] * gain;

        float* input_ptr  = mono_in;
        float* output_ptr = mono_out;

        uint32_t cyc0 = DWT->CYCCNT;
        nam_process(&nam_state,
                    (const float* const*)&input_ptr,
                    &output_ptr,
                    num_frames);
        uint32_t cyc1 = DWT->CYCCNT;

        uint32_t elapsed  = cyc1 - cyc0;
        cb_process_cycles = elapsed;
        if(elapsed > cb_max_cycles)
            cb_max_cycles = elapsed;

        for(size_t i = 0; i < num_frames; i++)
        {
            out[i * 2]     = mono_out[i] * volume;
            out[i * 2 + 1] = mono_out[i] * volume;
        }
    }
    else
    {
        for(size_t i = 0; i < num_frames; i++)
        {
            float s        = in[i * 2] * volume;
            out[i * 2]     = s;
            out[i * 2 + 1] = s;
        }
    }
}

int main(void)
{
    hw.Init();

    // FPDSCR sets the default FPSCR for all new FPU contexts (including ISRs).
    uint32_t fpscr = __get_FPSCR();
    fpscr |= (1U << 24) | (1U << 25);
    __set_FPSCR(fpscr);
    volatile uint32_t* FPDSCR = reinterpret_cast<volatile uint32_t*>(0xE000EF3C);
    *FPDSCR |= (1U << 24) | (1U << 25);

    hw.seed.StartLog(true);
    System::Delay(2000);
    hw.seed.PrintLine("NAMPedal (A2-nano C): booting...");

    hw.SetAudioBlockSize(kMaxBlockSize);

    SdmmcHandler::Config sd_cfg;
    sd_cfg.Defaults();
    sdcard.Init(sd_cfg);

    fsi.Init(FatFSInterface::Config::MEDIA_SD);
    FATFS&  fs        = fsi.GetSDFileSystem();
    FRESULT mount_res = f_mount(&fs, fsi.GetSDPath(), 1);
    hw.seed.PrintLine("FS mount: %s", mount_res == FR_OK ? "OK" : "FAILED");

    hw.seed.PrintLine("Loading model: model.namb");
    model_loaded = LoadModel("model.namb");
    hw.seed.PrintLine("Model load: %s", model_loaded ? "OK" : "FAILED");

    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;

    if(model_loaded)
    {
        for(size_t i = 0; i < kMaxBlockSize; i++)
            mono_in[i] = 0.0f;

        float* input_ptr  = mono_in;
        float* output_ptr = mono_out;

        DWT->CYCCNT = 0;
        nam_process(&nam_state,
                    (const float* const*)&input_ptr,
                    &output_ptr,
                    kMaxBlockSize);
        uint32_t cycles = DWT->CYCCNT;

        hw.seed.PrintLine("Benchmark: %lu cycles for %u frames (budget=480000)",
                          (unsigned long)cycles, (unsigned)kMaxBlockSize);
        hw.seed.PrintLine("  %.2f ms (deadline 1.00 ms)",
                          (float)cycles / 480000.0f);
    }

    hw.StartAdc();
    hw.StartAudio(AudioCallback);
    hw.seed.PrintLine("Audio engine started");

    hw.led1.Set(1.0f, 0.0f, 0.0f);
    hw.UpdateLeds();

    uint32_t last_print = System::GetNow();
    for(;;)
    {
        hw.ProcessAllControls();
        gain   = hw.GetKnobValue(DaisyPod::KNOB_1);
        volume = hw.GetKnobValue(DaisyPod::KNOB_2);

        if(hw.button1.RisingEdge())
        {
            effect_active = !effect_active;
            if(effect_active)
                hw.led1.Set(0.0f, 1.0f, 0.0f);
            else
                hw.led1.Set(1.0f, 0.0f, 0.0f);
            hw.UpdateLeds();
        }

        uint32_t now = System::GetNow();
        if(now - last_print >= 1000)
        {
            hw.seed.PrintLine(
                "cb=%lu  cycles=%lu  max=%lu  gain=%.3f  vol=%.3f  %s",
                (unsigned long)cb_count,
                (unsigned long)cb_process_cycles,
                (unsigned long)cb_max_cycles,
                gain,
                volume,
                effect_active ? "ACTIVE" : "BYPASS");
            last_print = now;
        }
    }
}
