// NAMPedal — Neural Amp Modeler running on a PedalPCB Terrarium (Daisy Seed,
// pure C inference)
//
// Loads an A2-nano NAM model in .namb (binary) format from the SD card and
// applies it to incoming audio in real time. Model inference uses the C code
// generated by nam2c.py with --dynamic-weights, so a single firmware image
// can run any A2-nano model by swapping the .namb on the SD card.
//
// Signal chain: input gain -> NAM model -> 3-band EQ -> output volume.
//
// Terrarium controls:
//   KNOB_1 = input gain   KNOB_2 = output volume   KNOB_3 = (unused)
//   KNOB_4 = bass         KNOB_5 = mid             KNOB_6 = treble
//   FOOTSWITCH_1 = bypass toggle   LED_1 = lit when effect active

#include "daisy_seed.h"
#include "terrarium.h"
#include "eq3band.h"
#include "model_data.h" // embedded NAM model (Terrarium has no SD card)
#include <cstring>

extern "C" {
#include "nam_model.h"
}

using namespace daisy;
using namespace terrarium;

static DaisySeed hw;

// Terrarium I/O: 6 knobs on Daisy pins D16..D21 (ADC channels 0..5), footswitch
// and bypass LED. The Terrarium::Knob enum remaps ADC channels to the physical
// knob layout, so reads go through it rather than the raw channel index.
static constexpr Pin kKnobPins[6]
    = {seed::D16, seed::D17, seed::D18, seed::D19, seed::D20, seed::D21};
static Switch footswitch;
static GPIO   led1;

static Eq3Band eq;

// Input gain ranges 0..2x (knob at noon == unity); output volume 0..1x.
static volatile float gain   = 1.0f;
static volatile float volume = 1.0f;
static volatile bool  effect_active = false;

// Model state lives in .bss (AXI SRAM). DTCM-resident ring buffers and
// weights are placed there by nam_model.c via NAM_DTCM. The model itself is
// the kModelData array in model_data.h, compiled into QSPI flash.
static nam_state_t nam_state;
static bool        model_loaded = false;

static constexpr size_t kMaxBlockSize = NAM_MAX_BUFFER_SIZE;
static float            mono_in[kMaxBlockSize];
static float            mono_out[kMaxBlockSize];

// A2-nano receptive field. Dilations × (kernel_size − 1) summed across layers:
//   layers  0–13: kernel=6,  dilations [1,3,7,17,41,101,239, 1,3,7,17,41,101,239] → 4090
//   layers 14–15: kernel=15, dilations [1,13]                                     →  196
//   layers 16–22: kernel=6,  dilations [1,3,7,17,41,101,239]                      → 2045
static constexpr int kPrewarmSamples = 1 + 4090 + 196 + 2045;

static constexpr uint32_t NAMB_MAGIC = 0x4E414D42; // "NAMB"

// Feed silence through the model until the receptive field is full.
static void Prewarm(int prewarm_samples)
{
    float zero_buf[NAM_MAX_BUFFER_SIZE];
    float out_buf[NAM_MAX_BUFFER_SIZE];
    memset(zero_buf, 0, sizeof(zero_buf));

    float* in_ptrs[NAM_IN_CHANNELS];
    float* out_ptrs[NAM_OUT_CHANNELS];
    for(int i = 0; i < NAM_IN_CHANNELS; i++)
        in_ptrs[i] = zero_buf;
    for(int i = 0; i < NAM_OUT_CHANNELS; i++)
        out_ptrs[i] = out_buf;

    int processed = 0;
    while(processed < prewarm_samples)
    {
        int n = NAM_MAX_BUFFER_SIZE;
        if(n > prewarm_samples - processed)
            n = prewarm_samples - processed;
        nam_process(&nam_state, (const float* const*)in_ptrs, out_ptrs, n);
        processed += n;
    }
}

// Parse the .namb model embedded in flash (model_data.h) and load its weights.
static bool LoadModel()
{
    const uint8_t* data = kModelData;
    uint32_t       size = kModelDataLen;
    hw.PrintLine("  embedded model: %u bytes", (unsigned)size);

    // .namb header (32 bytes):
    //   u32 magic, u16 version, u16 flags, u32 total_size,
    //   u32 weights_offset, u32 num_weights, u32 model_block_size, u32 checksum
    if(size < 32)
    {
        hw.PrintLine("  data too small for header");
        return false;
    }

    uint32_t magic;
    memcpy(&magic, data, 4);
    if(magic != NAMB_MAGIC)
    {
        hw.PrintLine("  bad magic: 0x%08lX", (unsigned long)magic);
        return false;
    }

    uint32_t weights_offset, num_weights;
    memcpy(&weights_offset, data + 12, 4);
    memcpy(&num_weights, data + 16, 4);

    hw.PrintLine("  weights: offset=%lu count=%lu",
                 (unsigned long)weights_offset,
                 (unsigned long)num_weights);

    if(weights_offset + num_weights * 4 > size)
    {
        hw.PrintLine("  weights extend beyond data");
        return false;
    }

    nam_init(&nam_state);

    // kModelData is 4-byte aligned, so this cast is safe to read as floats.
    const float* weights
        = reinterpret_cast<const float*>(data + weights_offset);
    int rc = nam_load_weights(weights, (int)num_weights);
    if(rc != 0)
    {
        hw.PrintLine("  nam_load_weights failed (not an A2-nano model?)");
        return false;
    }

    hw.PrintLine("  prewarming (%d samples)...", kPrewarmSamples);
    uint32_t t0 = System::GetNow();
    Prewarm(kPrewarmSamples);
    hw.PrintLine("  model ready (%lu ms)",
                 (unsigned long)(System::GetNow() - t0));
    return true;
}

static volatile uint32_t cb_count          = 0;
static volatile uint32_t cb_process_cycles = 0;
static volatile uint32_t cb_max_cycles     = 0;

static void AudioCallback(AudioHandle::InterleavingInputBuffer  in,
                          AudioHandle::InterleavingOutputBuffer out,
                          size_t                                size)
{
    // Force FZ/DN in this ISR context.
    __set_FPSCR(__get_FPSCR() | (1U << 24) | (1U << 25));

    cb_count++;
    size_t num_frames = size / 2;

    if(model_loaded && effect_active)
    {
        for(size_t i = 0; i < num_frames; i++)
            mono_in[i] = in[i * 2] * gain;

        float* input_ptr  = mono_in;
        float* output_ptr = mono_out;

        uint32_t cyc0 = DWT->CYCCNT;
        nam_process(&nam_state,
                    (const float* const*)&input_ptr,
                    &output_ptr,
                    num_frames);
        uint32_t cyc1 = DWT->CYCCNT;

        uint32_t elapsed  = cyc1 - cyc0;
        cb_process_cycles = elapsed;
        if(elapsed > cb_max_cycles)
            cb_max_cycles = elapsed;

        for(size_t i = 0; i < num_frames; i++)
        {
            float s        = eq.Process(mono_out[i]) * volume;
            out[i * 2]     = s;
            out[i * 2 + 1] = s;
        }
    }
    else
    {
        for(size_t i = 0; i < num_frames; i++)
        {
            float s        = in[i * 2] * volume;
            out[i * 2]     = s;
            out[i * 2 + 1] = s;
        }
    }
}

int main(void)
{
    hw.Init();

    // FPDSCR sets the default FPSCR for all new FPU contexts (including ISRs).
    uint32_t fpscr = __get_FPSCR();
    fpscr |= (1U << 24) | (1U << 25);
    __set_FPSCR(fpscr);
    volatile uint32_t* FPDSCR = reinterpret_cast<volatile uint32_t*>(0xE000EF3C);
    *FPDSCR |= (1U << 24) | (1U << 25);

    hw.StartLog(true);
    System::Delay(2000);
    hw.PrintLine("NAMPedal (A2-nano C): booting...");

    hw.SetAudioBlockSize(kMaxBlockSize);

    // 3-band EQ runs at the audio sample rate.
    eq.Init(hw.AudioSampleRate());

    // Terrarium knobs: 6 single-ended ADC channels on D16..D21.
    AdcChannelConfig adc_cfg[6];
    for(size_t i = 0; i < 6; i++)
        adc_cfg[i].InitSingle(kKnobPins[i]);
    hw.adc.Init(adc_cfg, 6);

    // Bypass footswitch (momentary, internal pull-up) and bypass LED (D22).
    footswitch.Init(hw.GetPin(Terrarium::FOOTSWITCH_1));
    led1.Init(seed::D22, GPIO::Mode::OUTPUT); // Terrarium::LED_1

    hw.PrintLine("Loading embedded model");
    model_loaded = LoadModel();
    hw.PrintLine("Model load: %s", model_loaded ? "OK" : "FAILED");

    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0;
    DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;

    if(model_loaded)
    {
        for(size_t i = 0; i < kMaxBlockSize; i++)
            mono_in[i] = 0.0f;

        float* input_ptr  = mono_in;
        float* output_ptr = mono_out;

        DWT->CYCCNT = 0;
        nam_process(&nam_state,
                    (const float* const*)&input_ptr,
                    &output_ptr,
                    kMaxBlockSize);
        uint32_t cycles = DWT->CYCCNT;

        hw.PrintLine("Benchmark: %lu cycles for %u frames (budget=480000)",
                          (unsigned long)cycles, (unsigned)kMaxBlockSize);
        hw.PrintLine("  %.2f ms (deadline 1.00 ms)",
                          (float)cycles / 480000.0f);
    }

    hw.adc.Start();
    hw.StartAudio(AudioCallback);
    hw.PrintLine("Audio engine started");

    led1.Write(false); // start bypassed

    // Track last-set EQ gains so coefficients are only recomputed (trig +
    // powf) when a knob actually moves, keeping the control loop cheap.
    float last_bass = 999.0f, last_mid = 999.0f, last_treble = 999.0f;

    uint32_t last_print = System::GetNow();
    for(;;)
    {
        footswitch.Debounce();

        // Knob reads (0..1) go through the Terrarium enum -> physical layout.
        gain   = hw.adc.GetFloat(Terrarium::KNOB_1) * 2.0f; // input, noon=unity
        volume = hw.adc.GetFloat(Terrarium::KNOB_2);        // output

        // EQ knobs: 0..1 -> +/-12 dB, center (0.5) == flat.
        float bass   = (hw.adc.GetFloat(Terrarium::KNOB_4) - 0.5f) * 24.0f;
        float mid    = (hw.adc.GetFloat(Terrarium::KNOB_5) - 0.5f) * 24.0f;
        float treble = (hw.adc.GetFloat(Terrarium::KNOB_6) - 0.5f) * 24.0f;
        if(bass != last_bass)
        {
            eq.SetBass(bass);
            last_bass = bass;
        }
        if(mid != last_mid)
        {
            eq.SetMid(mid);
            last_mid = mid;
        }
        if(treble != last_treble)
        {
            eq.SetTreble(treble);
            last_treble = treble;
        }

        if(footswitch.RisingEdge())
        {
            effect_active = !effect_active;
            led1.Write(effect_active);
        }

        uint32_t now = System::GetNow();
        if(now - last_print >= 1000)
        {
            hw.PrintLine("cb=%lu  cycles=%lu  max=%lu  gain=%.2f  vol=%.2f  "
                         "eq[%.1f %.1f %.1f]  %s",
                         (unsigned long)cb_count,
                         (unsigned long)cb_process_cycles,
                         (unsigned long)cb_max_cycles,
                         gain,
                         volume,
                         bass,
                         mid,
                         treble,
                         effect_active ? "ACTIVE" : "BYPASS");
            last_print = now;
        }
    }
}
